import 'dart:convert';

import 'package:crypto/crypto.dart';
import 'package:flutter/foundation.dart' show Uint8List;
import 'package:image/image.dart' as img;

// Provenance: the Canvas hashes were captured from Chromium on 2026-08-25
// using NovelAI's current drawImage/getImageData -> stealth cleanup order.
// The resize hashes were produced independently with official Pica 9.0.1
// Lanczos3 before the Dart port was implemented; Pica 10.0.3 has the same
// fixed-point resize core.
const sameSizeOpaqueRgbaSha256 =
    'f92084e6b4089f5402ae4c49e649dfc592b465f9e27a238afc9b36a001c6f83e';
const sameSizeTransparentRgbaSha256 =
    '1f5ed1e1d467fc3f71dab461accd6cadd896c98c31d9edf30dedeffbdaf9dc91';
const resizedLandscapeOpaqueRgbaSha256 =
    '55ab066fdb6e1067ed4928913537f2c88c14e614ff55ff34f6c9b6a8c531da43';
const resizedLandscapeTransparentRgbaSha256 =
    '0a9b779c34bf198e30bd4adcef42ff462063419760afc56ba837e1691e58cbe8';
const resizedPortraitOpaqueRgbaSha256 =
    'db60aef6ecd479a8e0a5c2c537d0c6eaa89563144b2e3ac4c283a4a33983f1e1';
const resizedPortraitTransparentRgbaSha256 =
    '1a72612206a32b296e24a6e32e0b7a5aca6b5f5c29c9ab39f80770d20c2df3d6';
const resizedOpaqueOnlyLandscapeRgbaSha256 =
    '9038659e168d2aeb6322d6c1b098bcb40816f365ed143f0ec62b17c53fb17d70';
const resizedOpaqueOnlyPortraitRgbaSha256 =
    '37367e80129a9b736436bcbd19c72483966e49019a3bdcaf195c20599bd3e68c';
const diagnosticResizedOpaqueRgbaSha256 =
    '76a56f004c11b375a800865751114d6bfd2f1d9008d272e94a93a7e70c093ddd';
const diagnosticResizedTransparentRgbaSha256 =
    '214dda7c62bc351077f3d24ce189566c6b9818bbb227e925f713f535799913eb';

Uint8List stealthCarrierPng({bool transparentTail = true}) {
  const width = 16;
  const height = 8;
  const magic = 'stealth_pngcomp';
  final image = img.Image(width: width, height: height, numChannels: 4);
  for (var y = 0; y < height; y++) {
    for (var x = 0; x < width; x++) {
      image.setPixelRgba(
        x,
        y,
        (x * 17 + y * 31) % 256,
        (x * 29 + y * 11) % 256,
        (x * 7 + y * 43) % 256,
        255,
      );
    }
  }
  final magicBytes = ascii.encode(magic);
  for (var bitIndex = 0; bitIndex < magicBytes.length * 8; bitIndex++) {
    final x = bitIndex ~/ height;
    final y = bitIndex % height;
    final bit = (magicBytes[bitIndex ~/ 8] >> (7 - bitIndex % 8)) & 1;
    final pixel = image.getPixel(x, y);
    image.setPixelRgba(x, y, pixel.r, pixel.g, pixel.b, 254 | bit);
  }
  // The first carrier bit is zero. Chromium turns 127 into 128 while
  // round-tripping this alpha-254 pixel through Canvas.
  image.setPixelRgba(0, 0, 127, 87, 85, 254);
  if (transparentTail) {
    image.setPixelRgba(15, 0, 127, 87, 85, 1);
    image.setPixelRgba(15, 1, 1, 3, 5, 128);
    image.setPixelRgba(15, 2, 254, 128, 64, 64);
    image.setPixelRgba(15, 3, 12, 34, 56, 0);
  }
  return Uint8List.fromList(img.encodePng(image));
}

/// Larger deterministic diagnostic sample retained separately from the
/// minimum boundary fixture. Its 37x29 hashes were captured with official
/// Pica 9.0.1 rather than generated by the Dart implementation under test.
Uint8List diagnosticStealthCarrierPng() {
  const width = 64;
  const height = 48;
  final image = img.Image(width: width, height: height, numChannels: 4);
  for (var y = 0; y < height; y++) {
    for (var x = 0; x < width; x++) {
      image.setPixelRgba(
        x,
        y,
        (x * 17 + y * 31) % 256,
        (x * 29 + y * 11) % 256,
        (x * 7 + y * 43) % 256,
        255,
      );
    }
  }
  final magicBytes = ascii.encode('stealth_pngcomp');
  for (var bitIndex = 0; bitIndex < magicBytes.length * 8; bitIndex++) {
    final x = bitIndex ~/ height;
    final y = bitIndex % height;
    final bit = (magicBytes[bitIndex ~/ 8] >> (7 - bitIndex % 8)) & 1;
    final pixel = image.getPixel(x, y);
    image.setPixelRgba(x, y, pixel.r, pixel.g, pixel.b, 254 | bit);
  }
  image.setPixelRgba(0, 0, 127, 87, 85, 254);
  image.setPixelRgba(63, 0, 127, 87, 85, 1);
  image.setPixelRgba(63, 1, 1, 3, 5, 128);
  image.setPixelRgba(63, 2, 254, 128, 64, 64);
  image.setPixelRgba(63, 47, 12, 34, 56, 0);
  image.setPixelRgba(0, 47, 33, 99, 201, 96);
  return Uint8List.fromList(img.encodePng(image));
}

String rgbaSha256(img.Image image) {
  final bytes = Uint8List(image.width * image.height * 4);
  var offset = 0;
  for (var y = 0; y < image.height; y++) {
    for (var x = 0; x < image.width; x++) {
      final pixel = image.getPixel(x, y);
      bytes[offset++] = pixel.r.toInt();
      bytes[offset++] = pixel.g.toInt();
      bytes[offset++] = pixel.b.toInt();
      bytes[offset++] = pixel.a.toInt();
    }
  }
  return sha256.convert(bytes).toString();
}

String bytesSha256(List<int> bytes) => sha256.convert(bytes).toString();
